version: '3.8'

services:
  app:
    image: sonechypurenko/raccoon-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # MongoDB Atlas URI
      SPRING_DATA_MONGODB_URI: mongodb+srv://raccoon:1111@cluster0.h997m.mongodb.net/raccoon?retryWrites=true&w=majority&appName=Cluster0
